# permissions for end users to edit accesspoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accesspoint-editor-role
rules:
- apiGroups:
  - accesspoint.ryusa.github.com
  resources:
  - accesspoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accesspoint.ryusa.github.com
  resources:
  - accesspoints/status
  verbs:
  - get
