# permissions for end users to view accesspointdevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accesspointdevice-viewer-role
rules:
- apiGroups:
  - accesspoint.ryusa.github.com
  resources:
  - accesspointdevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - accesspoint.ryusa.github.com
  resources:
  - accesspointdevices/status
  verbs:
  - get
