# permissions for end users to view accesspoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accesspoint-viewer-role
rules:
- apiGroups:
  - accesspoint.ryusa.github.com
  resources:
  - accesspoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - accesspoint.ryusa.github.com
  resources:
  - accesspoints/status
  verbs:
  - get
