apiVersion: accesspoint.ryusa.github.com/v1alpha1
kind: AccessPoint
metadata:
  name: accesspoint-sample
spec:
  ssid: raspberry
  password: password
  interface: wlan0
  bridge: br0
  nodeSelector: 
    accesspoint: sample
